config/routes.rb
Rails.application.routes.draw do
  resources :tutorials
  resources :categories
  resources :articles
  resources :users
  devise_for :students
  get "u/:username" => "home#profile", as: :profile

  # section to pair communities and posts.
  resources :communities do 
  resources :posts
  end 

  post "post/vote" => "votes#create"

  resources :subscriptions
  resources :comments, only: [:create]  
  #get 'home/index'
  get 'home/about'
  get 'home/tutorials'
  get 'home/interactive'
  get 'home/contact'
  get 'home/welcome'
  get 'home/privacy'
  get 'home/queue'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :student, optional: true
    belongs_to :category, optional: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_student!, except: [:index, :show]
  # GET /articles
  # GET /articles.json
  def index
    if params[:category].blank?
    @articles = Article.all
    else 
      @category_id = Category.find_by(name: params[:category]).id
      @articles = Article.where(category_id: @category_id)
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body, :image_url, :category_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, class: 'form-control', placeholder: 'Title of Article' %>
  </div>

  <div class="form-group">
    <%= form.text_area :body, class: 'form-control', placeholder: 'Article Body'  %>
  </div>

  <div class="form-group">
    <%= form.text_field :image_url, class: 'form-control', placeholder: 'Image URL'  %>
  </div>

  <div class = "c-select">
  <%= form.collection_select :category_id, Category.all, :id, :name, 
  {prompt: 'Choose a Category'}, class: 'form-control' %></div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-default btn-primary' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<%if request.original_url.split('=').last.include? '/' %>
<h1>Tutorials</h1>
<p></p>
<p>In order to assist students in developing a strong understanding of introductory programming concepts in Java, I have made a range of tutorials available to read and study.</p>
<p>Tutorials are stored in a blog format, and upon student request, new articles will be published. 
<p>Clicking on the blue-underlined title will take you to the desired page. Thank you!</p>
<br>
 <% else %> 
 <h1>All <%= request.original_url.split('=').last %> Articles</h1>
 <% end %>
 <h3>CS312 Articles/Tutorials</h3>
<p></p>
    <% @articles.each do |article| %>
  <li><%= link_to article.title, article %></li>
  <p></p>
    <%# <p><%= truncate(article.body, length: 200) %>
  <% end %>

  <br>
<h3>CS312 Categories</h3>
<p> Categories inspired by the curriculum mapped out on Professor John's Website.</p>
<div class = "container">
<div class = "row">
  <div class = "col-lg-10"> 
  <ul class = "nav nav-pills nav-stacked">
  <%# <li> <%= link_to 'All Categories', root_path %> </li>
  <% Category.all.each do |category| %>
  <li> <%= link_to category.name, articles_path(category: category.name)%>
  <% end %>
  </ul>
  </div>
  </div>
  </div>



 <% if current_student && current_student.admin %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="5"></th>
    </tr>
  </thead>
<br>
<br>

<div class="card">
</div>
<p></p>
<h3> Article Creation Panel (For Administrators Only)</h3>
<p></p>
<div class="card">
</div>
<p></p>
<p></p>
<p> Hello instructor! This button will navigate you to the page where a new article can be created.</p>
<p> Please email <b>omeed@cs.utexas.edu</b> for any questions.</p>
<p></p>
<p></p>
<%= link_to 'New Article', new_article_path, class: "btn btn-primary" %>
<br>
<br>
<div class="card">
</div>
<p></p>
<p></p>
<h3> Article Management Panel (For Administrators Only)<h3>
<p></p>
<div class="card">
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %> &nbsp &nbsp</td>
        <%# <td><%= truncate(article.body, length: 30) %>
        <%# <td><%= article.image_url %>
        <td><%= link_to 'Show', article, class: 'btn btn-danger' %></td>
        <td><%= link_to 'Edit', edit_article_path(article), class: 'btn btn-danger' %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
      </div>
     <% end %>
  </tbody>
</table>
<br>
<% end %>
<br>
<br>
<br>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<style> 
  img {
    max-width: 200px;
    max-height: 200px;
  }
</style>


<p id="notice"><%= notice %></p>

<h1>   <%= @article.title %> </h1>

<p class = "img">
    <%= image_tag @article.image_url, align: 'right' %>
      <%= @article.body %>
</p>
<% if student_signed_in? %>
<%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>
<%= link_to 'Back', articles_path %>