config/routes.rb
Rails.application.routes.draw do
  resources :tutorials
  resources :categories
  resources :articles
  resources :users
  devise_for :students
  get "u/:username" => "home#profile", as: :profile

  # section to pair communities and posts.
  resources :communities do 
  resources :posts
  end 

  post "post/vote" => "votes#create"

  resources :subscriptions
  resources :comments, only: [:create]  
  #get 'home/index'
  get 'home/about'
  get 'home/tutorials'
  get 'home/interactive'
  get 'home/contact'
  get 'home/welcome'
  get 'home/privacy'
  get 'home/queue'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Friend profile was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Friend profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Friend profile was successfully destroyed from the database.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <div class="field form-group">
    <p>What is your first name? </p>
    <%= form.text_field :first_name, class: "form-control",  placeholder: "First Name" %>
  </div>
  <br>

  <div class="field form-group">
    <p>What is your last name? </p>
    <%= form.text_field :last_name, class: "form-control" , placeholder: "Last Name"%>
  </div>
  <br>

  <div class="field form-group">
    <p>What is your email? </p>
    <%= form.text_field :email, class: "form-control" , placeholder: "Email"%>
  </div>
  <br>

  <div class="field form-group">
    <p>What is your mobile phone number? </p>
    <%= form.text_field :phone , class: "form-control", placeholder: "Phone Number" %>
  </div>
  <br>
  <div class="field form-group">
    <p>What is one sentence that describes you?</p>
    <%= form.text_field :twitter, class: "form-control", placeholder: "My Answer" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
    <%# <p style="float: right;" >
    <img src="https://static6.depositphotos.com/1035649/599/v/600/depositphotos_5993687-stock-illustration-friendship.jpg" 
    height="30%" width="30%"></p> %>
<style>
.button {
  position: relative;
  background-color: #4CAF50;
  border: none;
  font-size: 28px;
  color: #FFFFFF;
  padding: 20px;
  width: 200px;
  text-align: center;
  transition-duration: 0.4s;
  overflow: hidden;
}


.button:active:after {
  padding: 0;
  margin: 0;
  opacity: 1;
  transition: 0s
}
</style>

    <h1>Find Friends in CS312</h1>

<br>
<h3>About Friend Finder</h3>
<p>During these times, it can be hard to connect with fellow classmates. We completely understand that.</p>
<p>Studies have shown that when group studying is done correctly, it can have SEVERAL advantages vs. studying alone.</p>
<p>Research done by a behavioral scientist showed that studying in groups actually increases the chance of processing difficult conceptual topics.</p>
<p>Don't be scared to reach out to fellow classmates, but keep ALL academic integrity information in mind.</p>
<p>You can access the academic integrity in UTCS presentation here: <a href = "https://www.cs.utexas.edu/~scottm/misc/Academic_Integrity.pdf" >https://www.cs.utexas.edu/~scottm/misc/Academic_Integrity.pdf</a></p>
<h3>Instructions:</h3>
<ol>
<li>Press the new social profile button to create a profile in our database.</li>
<li>Look around in the list and pick a few people to reach out to!</li>
</ol>
<h3>Rules and Notices</h3>
<li>Please note that for security reasons, we do not allow the editing or removal of a profile.</li>
<li>Please refrain from creating multiple profiles or trolling.</li>
<li>Please provide accurate information so that classmates can reach out without hassle.</li>
<li>For permanent removal of friend profile, please contact the website administrator.</li>
<br> 


<h3> Create Profile </h3>
<p></p>
<%= link_to 'Create New Profile', new_user_path, class: "btn btn-primary"%>
<br>
<br>

<table class="table table-striped table-bordered">
  <div class="table-responsive">

 <thead>
    <tr>
      <th>First Name &nbsp;&nbsp;&nbsp; </th>
      <th>Last Name&nbsp;&nbsp;&nbsp; </th>
      <%# <th>Email&nbsp;&nbsp;&nbsp; </th> %>
      <th>Contact Information&nbsp;&nbsp;&nbsp; </th>

      <%# <th>Email &nbsp;&nbsp;&nbsp;</th>
      <th>Phone</th>
      <th>Twitter</th> %>
      <%# <th colspan="3"></th> %>
    </tr>
  </thead>
<h3>Current Profiles</h3>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <%# <td><%= user.email %></td>
        <%# <td><%= user.phone %></td> 
        <%# <td><%= user.twitter%></td>  
        <td><%= link_to 'Show More', user, class: "btn btn-primary" %></td>

        <% if current_student && current_student.admin %>
        <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', user, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>


      </tr>
    <% end %>
  </tbody>
  </table>

  </div>


<br>

app/views/users/new.html.erb
<h1>New Friend Profile</h1>

<%= render 'form', user: @user %>

<p></p>
<%= link_to 'Back', users_path, class: "btn btn-secondary" %>

app/views/users/show.html.erb
<div class = "container">

<h3>   <%= @user.first_name %>'s Profile </h3>
<div class="card">
  <div class="card-body">
    <h5 class="card-title">  <%= @user.first_name %> <%= @user.last_name %></h5>
    <p class="card-text">  <%= @user.twitter %> </p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><%= @user.phone %></li>
    <li class="list-group-item">  <%= @user.email %></li>
  </ul>
  <div class="card-body">
    <%= link_to 'Back', users_path, class: "btn btn-primary" %>
  </div>
</div>
</div>
<br>
<% if current_student && current_student.admin %>
<h3>Student Profile Management (Administrator Access Only)</h3>
</p>
<%= link_to 'Edit Student Profile', edit_user_path(@user) , class: "btn btn-danger" %> 
<% end %>