config/routes.rb
Rails.application.routes.draw do
  resources :tutorials
  resources :categories
  resources :articles
  resources :users
  devise_for :students
  get "u/:username" => "home#profile", as: :profile

  # section to pair communities and posts.
  resources :communities do 
  resources :posts
  end 

  post "post/vote" => "votes#create"

  resources :subscriptions
  resources :comments, only: [:create]  
  #get 'home/index'
  get 'home/about'
  get 'home/tutorials'
  get 'home/interactive'
  get 'home/contact'
  get 'home/welcome'
  get 'home/privacy'
  get 'home/queue'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # home page
  def index
    @communities = Community.all.limit(5)
    @posts = Post.limit(20).sort_by{ |p| p.score }.reverse
    @posts = Post.order(id: :desc).limit(20)
  end

  # about page
  def about
  end

  # tutorials page
  # def tutorials
  #   @tutorials = Tutorial.where(parent_id: nil)
  # end

  #contact page
  def contact
  end

  def interactive
  end

  def welcome
  end

  def privacy
  end

  def queue
  end

  def profile 
    @profile = Student.find_by_username params[:username]
    @posts = @profile.posts
  end 

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
footer

app/views/home/_header.html.erb
<style>
.margin {
  margin-right: 10px;
}
</style>

 <%# <% if student_signed_in? %>
<nav class="box-shadow: 10px navbar navbar-expand-lg navbar-dark bg-dark border-bottom">
  <div class="container-fluid">
  <a href = "https://cs.stanford.edu/people/karpathy/convnetjs/">
  <img  class = "margin" src="https://www.pngkey.com/png/full/396-3960421_abstract-png-transparent-images-connect-the-data-dots.png" width="40" height="40"/></a>
    <%= link_to ' CS312 Learning Hub', root_path, class: 'navbar-brand'%>
    
    <%# <a class="navbar-brand" href="#">CS312 Learning Hub</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      
        <% if student_signed_in? %>
         <li class="nav-item">
         <%= link_to 'Home', root_path, class: 'nav-link'%>
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
        </li>
          <li class="nav-item">
         <%= link_to 'Find Friends', users_path, class: 'nav-link'%>
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
        </li>
        <li class="nav-item">
         <%= link_to 'Interactive Learning', home_interactive_path, class: 'nav-link'%>
        </li>
       <li class="nav-item">
        <%= link_to "Office Hour Queue", home_queue_path, class: "nav-link" %>
          <%# <a class=" nav-link" href="#">Tutorials</a> %>
        </li>
        <%# <li class="nav-item"> %>
        <%# <%= link_to "Class Blog", articles_path, class: "nav-link" %>
          <%# <a class=" nav-link" href="#">Tutorials</a> %>
        <%# </li> %>
        <li class="nav-item">
        <%= link_to "Tutorials", tutorials_path, class: "nav-link" %>
          <%# <a class=" nav-link" href="#">Tutorials</a> %>
        </li>
        <li class="nav-item">
         <%= link_to 'Edit Profile', edit_student_registration_path, class: 'nav-link'%>
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
        </li>
          <li class="nav-item">
         <%= link_to 'Sign Out',  destroy_student_session_path, method: :delete, class: 'nav-link'%>
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
        </li>
        <% else %>
                 <li class="nav-item">
         <%= link_to 'Sign Up', new_student_registration_path, class: 'nav-link'%>
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
        </li>
          <li class="nav-item">
         <%= link_to 'Sign In', new_student_session_path, class: 'nav-link'%>
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
        </li>

          <li class="nav-item">
         <%= link_to 'Contact Us', home_contact_path, class: 'nav-link'%>
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
        </li>
          <li class="nav-item">
         <%= link_to 'Privacy Policy', home_privacy_path, class: 'nav-link'%>
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
        </li>
        <% end %>



      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/_homepageheader.html.erb
    <script>
$(document).ready(function(){
        $("#myCarousel").carousel();
});
</script>
    
    <div class = "row" >
        <div class = "col-12 pt-3 pb-3 mb-4 border-bottom " >
            <div class = "align-items-end">

          <div class = "float-end">




              
          <a class="btn btn-primary dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <div class = "karma float-end">
         &nbsp;<span class = "fa fa-star text-warning"></span>
         <%= current_student.engagement %>
          </div>
        <%= current_student.full_name %> 
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Homepage", root_path, class: "dropdown-item" %>
          <%= link_to "Create New Community", new_community_path, class: "dropdown-item"%>
          <hr class="dropdown-divider">
           <%= link_to "View Public Profile", profile_path(current_student.username), class: "dropdown-item" %>
          </ul>
        </div>
        </div>  
<p class = "h2"> <%= link_to "CS312 Student Homepage", root_path, class: "text-decoration-none" %></p>
</div>  
</div>
</div>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<style>

.welcome {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-pack: center;
        -ms-flex-pack: center;
            justify-content: center;
    -webkit-box-align: center;
        -ms-flex-align: center;
            align-items: center;
}

.footer {
  position: fixed;
  left: 0;
  bottom: 2%;
  width: 100%;
  background-color: transparent;
  color: white;
  text-align: center;
}
.imageStyle {
   width: 100%;
  height: auto;
}

.margin {
  margin-left: 5%;
}

/* Header */
.large-header {
	position: relative;
	width: 100%;
	background: #333;
	overflow: hidden;
	background-size: cover;
	background-position: center center;
	z-index: 1;
}

#large-header {
	background-image: url('https://www.marcoguglie.it/Codepen/AnimatedHeaderBg/demo-1/img/demo-1-bg.jpg');
}

.main-title {
	position: absolute;
	margin: 0;
	padding: 0;
	color: #f9f1e9;
	text-align: center;
	top: 50%;
	left: 50%;
	-webkit-transform: translate3d(-50%,-50%,0);
	transform: translate3d(-50%,-50%,0);
}

.demo-1 .main-title {
	text-transform: uppercase;
	font-size: 4.2em;
	letter-spacing: 0.1em;
}

.main-title .thin {
	font-weight: 200;
}

.removelinkdefault {
    color: black;
    text-decoration: none;
}

.carousel{
    background: #2f4357;
    margin-top: 20px;
}
.carousel-item{
    text-align: center;
    <%# min-height: 280px; /* Prevent carousel from being distorted if for some reason image doesn't load */ %>
	max-height: 325px;
}

@media only screen and (max-width : 768px) {
	.demo-1 .main-title {
		font-size: 3em;
	}
}
</style>

<% if student_signed_in? %>
<p></p>
<%# <div class = imageStyle> %>
    <%# <p style="float: right;"> %>
    <%# <img src="https://www.pngkey.com/png/full/396-3960421_abstract-png-transparent-images-connect-the-data-dots.png" height="90%" width="90%"></p> %>
    <%# <h2>Welcome to CS312 (Introduction to Programming) Learning Hub!</h2> %>
	<%= render 'home/homepageheader' %>
	<section class = "bg-light">
	<div class = "container">
	

<div class="container-md my-3">
		    <h4>Live Feed</h4>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Carousel indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <!-- Wrapper for carousel items -->
        <div class="carousel-inner">
            <div class="carousel-item active">
            <img src="https://cutewallpaper.org/21/texas-longhorn-wall-paper/Texas-Longhorn-Free-Wallpaper-and-Backgrounds-Larutadelsorigens.jpg" alt="First Slide">
			      <div class="carousel-caption d-none d-md-block float-end">
        	<h4>Greetings, <%= current_student.full_name %>.</h4>
			<p>Welcome to CS312 Learning Hub.</p>
			<p>
      		</div>
            </div>
			
            <div class="carousel-item">
            <img src="https://capitalplanning.utexas.edu/sites/cpc.utexas.edu/files/styles/lightbox_full/public/completedprojects/102-254-Dell-GSC-1.jpg?itok=s5hk_Dss" alt="Second Slide">
            </div>
            <div class="carousel-item">
            <img src="https://media-exp1.licdn.com/dms/image/C4E1BAQGE8BaPuk0HmQ/company-background_10000/0/1519796738414?e=2159024400&v=beta&t=u3jPJLgYzigwsupX71LndMUNku2JwIDSGt_ZwOwKbwc" alt="Third Slide">
            </div>
        </div>
        <!-- Carousel controls -->
        <a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
</div>




	<div class = "row">
	<%# <div class = "col-sm-3">
	Topic #1
	</div>
		<div class = "col-sm-3">
			Topic #2
	</div>
		<div class = "col-sm-3">
			Topic #3
	</div>
		<div class = "col-sm-3">
			Topic #4
	</div> %>
	</div>
	<br>
	<p>
	<div class = "row">
	<div class = "col">
	<h4>Recent Posts in CS312 Forums</h4>
	<p>
	</div>
	</div>

	<div class = "row">
	

<div class = "row">
<div class = "col-8">
	<%= render partial: "posts/list", locals: { posts: @posts }%>
	</div>
	

	<div class = "col-4">
	<h5> Important Topics / Assignments</h5>
	<ul class="list-group">
	<% @communities.each do |community| %>
  	<li class="list-group-item"> <%= link_to community.name, community_path(community), class: "text-decoration-none"%> </li>
	</ul>
	<% end %>
		<%= link_to "View All", communities_path, class: "btn btn-primary mt-3"%>
	</div>
	</div>
	</div>
	</div>



</div>
<p></p>
</section>
<%# <footer>
<div class = "footer">
<a href="https://cs.utexas.edu">
 <img  src="https://www.cs.utexas.edu/~gill/images/UTA_CS_logo.png" alt="", style="width:35%;height:35%;">
</div>
</a>
</footer> %>

<% else %>
	<div class="alert alert-primary" role="alert">
 	<b>To Beta Testers:</b> Over the course of the next couple weeks, expect several bugs. Regardless of seriousness, please report them to me!
	</div>	
	<br>
	<div class = "container">
    <%# <p style="float: right;"class = "margin" >
 	<div class = "margin"> %>
  	<%# <h3>Welcome to the CS312 (Intro to Programming) Learning Hub!</h3> %>
	  <div class = "welcome">
	  	  	<h1>Welcome to the CS312 Learning Hub! &nbsp;</h1>
	  	    <img src="https://www.pngkey.com/png/full/396-3960421_abstract-png-transparent-images-connect-the-data-dots.png" style="width: 130px;">
	</div>
	<hr>
	<h4>Introduction</h4>
	<p>Greetings! My name is <a href = "https://cs.utexas.edu/~omeed"> Omeed Tehrani</a> and I am the founder and creator of the CS312 Learning Hub. During my winter break, I built this website for students in hopes of making the learning experience of introductory programming concepts more interactive, fun and enjoyable. In my opinion, the difficulty of Java lies in its abstraction and attention to detail that makes a huge differences the programmer's code cleanliness and correctness. Trust me, I completely understand that COVID-19 has been difficult, but as long as we interact and work together, we're going to get through this pandemic together & you will come out this class feeling like a better programmer and a champion.
	<p>Below this section, there is a great deal of information about the website and how to use it. If you are new, please read the instructions thoroughly. If you are a returning user, please navigate to the "Sign In" tab. Student account information is inaccesible in the database for privacy reasons, so please take your time in the account creation process.</p>
	<hr>
	<h4>Account Registration</h4>
	<p> Each student is permitted to register one account in the database. This account is designed to give the student a personalized experience on the learning application. Please refrain from registering multiple accounts. If you would like to create a new account with another email, please navigate to the "Manage Account" section after you have logged in and delete your account from the database.</p>
	<em> To get started on account registration, follow the steps below: </em>
	<ol>
	<li> Navigate to the tab above and select "Sign Up". </li>
	<li> Fill in all the required fields & ensure that you select a unique and secure password. </li>
	<li> The website will then show you a notification instructing to check your email for account verification steps</li>
	<li> After waiting approximately 1 to 2 minutes, the system will automatically send the email.</li> 
	<li> You should look for an email titled "CS312 Learning Hub - Confirmation Instructions" from the address: <a href = "mailto:cs312hub@gmail.com"> cs312hub@gmail.com</a> </li>
	<li> After finding the email, please read it thoroughly. If you did not recieve the email, I would recommend checking your spam folder (Sometimes this occurs because the mail server is recieving an email from an unknown IP or unknown address).</li>
	<li> Select the link labeled "CONFIRM MY ACCOUNT" to activate your account. If the confirmation token is recent and valid, you will see a notification on the website telling you that your email has been confirmed.</li>
	<li> This means that your account is now activated. You can now navigate to the tab that is labeled "Sign In" and log in with your previously created credentials.</li>
	<li> After signed in, the navigation bar will unlock a whole new set of tabs, and your learning hub experience has begun!</li> 
	<li> <em> Please note:</em> The system will not allow a login until the account has been activated. </li>
    <%# <h2>Welcome to CS312 (Introduction to Programming) Learning Hub!</h2> %>
	</ol>
	<hr>
	<h4>Features</h4>
	<p> After approximately 55 Beta versions, this application has reached the first stage of deployment for students. Please note that I am constantly looking for new features to add. If you have any recommendations, please reach out to me at my email (<a href= "mailto:omeed@cs.utexas.edu">omeed@cs.utexas.edu</a>) with a descriptive subject line such as "Feature Recommendation".
	<li>Personalized Student Profile</li>
		<li>Personalized Student Homepage</li>
	<li>Engagement Point Tracker</li>
		<li>Public and Private Profile Management</li>
	<li>Friend/Classmate Finder</li>
	<li>Office Hour Queue (provided generously by CS314 developers)</li>
	<li>Interactive Learning</li>
		<li>Concept Wikis/Tutorials</li>
				<li>Concept Posts (Organized by Communities)</li>
	<li>Post Engagement Ability</li>
	<hr>
	<h5>Development Information</h5>
	<p>This web application was created from the ground up using the <a href = "https://rubyonrails.org/"> Ruby on Rails</a>, an open source, server-side framework that has gotten multiple <a href = "https://contributors.rubyonrails.org/"> contributions</a> and is the basis of popular applications such as Shopify and Twitch. This framework is written in Ruby, the programming language, and used alongside Rails. To any student who is looking to build a web application, I highly recommend this framework.</p>
	<p>The hosting of this application is done through <a href = "https://heroku.com/"> Heroku</a>, a cloud application platform supporting several programming languages. This application does not contain any add-ons, but uses the SendGrid mail application to reroute emails to students after registration. The application is upgraded to use Hobby Development Dynos, but will be upgraded according to usage and scale. As of present day, there have been 100+ updates to GitHub, and about 55 deployments from GitHub to the heroku development branch, but of course, this number will increase as new features are added and new bugs are found.</p> 
	<p>If you are not currently a student, or are a former student looking for a side project, please personally reach out to me through email, as I will be recruiting developers to help improve and expand this application and many others for my SaaS company launching sometime this year. No experience is required.</p>
	<hr>
	<br>
	<footer>
     <center>
      <img width="35%" src = "https://www.cs.utexas.edu/sites/all/themes/utcs2/images/cslogo.svg">
    </center>
      <!-- $Social-->
   <footer>
       <br>    
</div>
<div>
<%# <center>
<img bottom = 0 href = "https://cs.utexas.edu" src="https://www.cs.utexas.edu/sites/all/themes/utcs2/images/cslogo.svg" 
alt="" 
width = "30%">
</center>
<div> %>
<p></p>


<% end %>

app/views/home/interactive.html.erb
<h3>Interactive Learning<h3>

app/views/home/profile.html.erb
<div class = "row">
<div class = col-sm-8>
<h4> My Engagement Activity </h4>
<p>
    <%= render partial: "posts/list", locals: {posts: @posts} %>
</div>
<div class = "col-sm-4 bg-light ">
    <br>
    <h4><%= @profile.full_name %></h4>
   <h5> <%= @profile.username %></h5>
   <p><em><%= @profile.bio %></p></em>
   <p><em>Student Engagement Score:</em> <%= @profile.engagement %> <span class = "fa fa-star text-warning"></span> </p>
    <p><em>Date Joined:</em> <%= @profile.created_at.strftime("%m/%d/%Y") %></p>
    <br>
</div>
</div>

app/views/home/queue.html.erb

<div> 
<h3>CS312 Office Hours Queue</h3>
<p></p> 
<p> The CS312 Office Hour Queue is designed to make office hours easier to attend for students who might have questions on course content in the class.</p>
<p> The server for this queue is run on another website, so please click the button below to navigate.</p>
<a  href = "https://cs312.utcshelphours.com">
<button  class = "btn btn-primary">TAKE ME TO OFFICE HOURS →</button></div></a>

app/views/home/welcome.html.erb
<h1>Welcome Page!<h1>