config/routes.rb
Rails.application.routes.draw do
  resources :tutorials
  resources :categories
  resources :articles
  resources :users
  devise_for :students
  get "u/:username" => "home#profile", as: :profile

  # section to pair communities and posts.
  resources :communities do 
  resources :posts
  end 

  post "post/vote" => "votes#create"

  resources :subscriptions
  resources :comments, only: [:create]  
  #get 'home/index'
  get 'home/about'
  get 'home/tutorials'
  get 'home/interactive'
  get 'home/contact'
  get 'home/welcome'
  get 'home/privacy'
  get 'home/queue'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
    belongs_to :parent, class_name: "Tutorial", optional: true
    has_many :subtutorials, class_name: "Tutorial", foreign_key: :parent_id, dependent: :destroy
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController

  def index
    @tutorials = Tutorial.where(parent_id: nil)
  end
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/tutorials/_form.html.erb
<%= form_with(model: tutorial) do |form| %>
  <% if tutorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tutorial.errors.count, "error") %> prohibited this tutorial from being saved:</h2>

      <ul>
        <% tutorial.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tutorials/edit.html.erb
<h1>Editing Tutorial</h1>

<%= render 'form', tutorial: @tutorial %>

<%= link_to 'Show', @tutorial %> |
<%= link_to 'Back', tutorials_path %>

app/views/tutorials/index.html.erb
<p id="notice"><%= notice %></p>

    <% @tutorials.each do |tutorial| %>
      <p><%= tutorial.name %></p>
      <% tutorial.subtutorials.each do |subtutorial| %>
      <%= subtutorial.name%>
        <% end %>
      <% end %>

<h1>Tutorials</h1>
<p></p>
<p>In order to assist students in developing a strong understanding of introductory programming concepts in Java, I have made a range of tutorials available to read and study.</p>
<p>Tutorials are stored in a blog format, and upon student request, new articles will be published. 
<p>Clicking on the blue-underlined title will take you to the desired page. Thank you!</p>
<br>



<%# <%= link_to 'New Tutorial', new_tutorial_path %> 

app/views/tutorials/new.html.erb
<h1>New Tutorial</h1>

<%= render 'form', tutorial: @tutorial %>

<%= link_to 'Back', tutorials_path %>

app/views/tutorials/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tutorial_path(@tutorial) %> |
<%= link_to 'Back', tutorials_path %>